name: Environment Secret Example

on: [push]

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use API key
        run: echo "API_KEY is ${{ secrets.API_KEY }}"
